### ISSUE TITLE
Webhook helper constant time equality

### ISSUE THREAD

**Issue by alexy4744** [square/square-nodejs-sdk#129]
It seems like the webhook helper does not use constant time equality to compare the expected signature with the calculated signature, which opens up the possibility of a timing attack.

https://github.com/square/square-nodejs-sdk/blob/37781b672fd7faceb4a42afb5cf3b2b2b5aa0c06/src/utilities/webhooksHelper.ts#L43

**Comment by zenmasterjobo** [comment]
Hey @alexy4744,

Thanks again for bringing this to our attention! I just wanted to follow up and point something out with our implementation here, and why our comparison is not susceptible to a timing attack.

Both values at time of comparison are hashed values used from the Sha-256 hashing algorithm. Sha-256 will always output a fixed length of 32 bytes, and commonly read as a hex string that is 64 characters long.

Because of this, the two values being compared in your code snippet provided will always be the same length, therefore an attacker would not be able to fish for values using a timing attack. 

Thanks again for calling this out though, but I will be closing this ticket as the suggested attack vector is not viable here.

Take care, and please continue to report other findings you may have :)
