### ISSUE TITLE
CatalogItem / ecomSeoData API should not return undefined.

### ISSUE THREAD

**Issue by kyeshmz** [square/square-nodejs-sdk#151]
**Describe the bug**
In the Squareup.com GUI, we can see that the SEO option populates avaliable fields using item name and description by default. 
This is not the case when calling it through the API. Also there is no option to make it the same as the item name, as this also renders the SEO field such as permalink to be undefined.

**Expected behavior**
Permalink should return the default name, as is explained in the web GUI.

Currently, in the SDK ecomSeoData can be undefined, with the fields being able to be null.
This should not be the case because they would be default defined as the name.
```
/** SEO data for for a seller's Square Online store. */
export interface CatalogEcomSeoData {
    /** The SEO title used for the Square Online store. */
    pageTitle?: string | null;
    /** The SEO description used for the Square Online store. */
    pageDescription?: string | null;
    /** The SEO permalink used for the Square Online store. */
    permalink?: string | null;
}
```

**To Reproduce**
Steps to reproduce the bug:
1. Create a menu with the necessary fields
2. Try to retreieve the item and parse ecomSeoData.

**Screenshots**

![Screenshot 2024-06-17 at 2 23 29 PM](https://github.com/square/square-nodejs-sdk/assets/12763472/bba17666-6538-4046-a9d6-2c8114b39cf8)

**Square SDK version**
		"square": "^37.1.0",

**Comment by zenmasterjobo** [comment]
hi @kyeshmz 

I agree this is a confusing interface, however this is currently working as expected.

Basically the `ecomSeoData` is using the item name and item description as the default values of those fields (pageTitle, pageDescription, permalink) but because they are just pointing to those fields which are set on the item itself, the seo data is not returned as part of the itemData.

If you change those fields in the GUI to something different, those values will return on the item when you query it through the API.

I raised this concern with the team though, and will update this ticket if they decide to change the behavior. Thank you for calling this out!

**Comment by kyeshmz** [comment]
I understand, like the idea, but not the implementation.

>but because they are just pointing to those fields which are set on the item itself,

For example, if this was a pointer, this would not be null if the name or description was defined. It seems to me like it should just return both.
