### ISSUE TITLE
Cors error accessing v2/payments even w/HTTPS Certification

### ISSUE THREAD

**Issue by stalliw** [square/square-nodejs-sdk#37]
I am attempting to access v2/payments Api through the client side in Chrome. I have Https certification through Netlify but I am still receiving a block through the Cors Policy. Does the Api support Cors? I also can't reach from my localhost but I'd expect that. 

![error](https://user-images.githubusercontent.com/72957360/120212297-cae8ae80-c1ff-11eb-9ba4-27956aa0a779.PNG)

**Comment by stalliw** [comment]
I'm still having issues on this topic after many days of research. I have full TLS & HTTPS Certification but getting the same Cors error even though I specific request headers in my file

**Comment by wolfadex** [comment]
We do not currently support using the NodeJS SDK on the frontend, which is why you're getting CORS issues. By using the SDK in the frontend you'd be exposing your secret access token to anyone who uses your app. You'd need to use one of our backend SDKs (this [NodeJS](https://github.com/square/square-nodejs-sdk) one, [.NET](https://github.com/square/square-dotnet-sdk), [Ruby](https://github.com/square/square-ruby-sdk), [Python](https://github.com/square/square-python-sdk), [PHP](https://github.com/square/square-php-sdk), or [Java](https://github.com/square/square-java-sdk)) or access the API directly with the language of your choice.

**Comment by stalliw** [comment]
Thanks @wolfadex ! This answers my question
