### ISSUE TITLE
why can't `expMonth` and `expYear` be `number` instead of `bigint` ?

### ISSUE THREAD

**Issue by rawatnaresh** [square/square-nodejs-sdk#48]
All I'm trying to do it return the response from `cardsApi` 

```js
const data = await cardsApi.createCard({
    ...
});
...
return res.status(200).json({ card: data.result.card });
```

But I'm getting an error because `expMonth` and `expYear` are bigint

![Screen Shot 2021-07-14 at 12 26 09](https://user-images.githubusercontent.com/29520305/125575853-abbe3214-e121-4425-9fd4-c8d8f1781424.png)

**Comment by wolfadex** [comment]
Hi @rawatnaresh I can definitely see this being an issue. The short answer is because those fields are 64 bit Integers ([see here in the docs](https://developer.squareup.com/reference/square/objects/Card)). I will see what I can do to make this a better experience.

For a more immediate solution I'd recommend checking out https://github.com/square/square-nodejs-sdk/issues/24#issue-839842933 as it notes the more general issue of values that are BigInt and how to handle sending them over http.
